# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Anaekran(object):
    def setupUi(self, Anaekran):
        Anaekran.setObjectName("Anaekran")
        Anaekran.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Anaekran)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 120, 481, 181))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 0, 551, 121))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 330, 701, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        Anaekran.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Anaekran)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuBilgiler = QtWidgets.QMenu(self.menubar)
        self.menuBilgiler.setObjectName("menuBilgiler")
        self.menusubeislemleri = QtWidgets.QMenu(self.menuBilgiler)
        self.menusubeislemleri.setObjectName("menusubeislemleri")
        self.menusfizikiislemler = QtWidgets.QMenu(self.menuBilgiler)
        self.menusfizikiislemler.setObjectName("menusfizikiislemler")
        self.menudagitim = QtWidgets.QMenu(self.menubar)
        self.menudagitim.setObjectName("menudagitim")
        self.YeniDagitim = QtWidgets.QMenu(self.menudagitim)
        self.YeniDagitim.setObjectName("YeniDagitim")
        Anaekran.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Anaekran)
        self.statusbar.setObjectName("statusbar")
        Anaekran.setStatusBar(self.statusbar)
        self.OkulBilgileriGuncelle = QtWidgets.QAction(Anaekran)
        self.OkulBilgileriGuncelle.setObjectName("OkulBilgileriGuncelle")
        self.EskiDagitimlar = QtWidgets.QAction(Anaekran)
        self.EskiDagitimlar.setObjectName("EskiDagitimlar")
        self.SubeisimleriGuncelle = QtWidgets.QAction(Anaekran)
        self.SubeisimleriGuncelle.setObjectName("SubeisimleriGuncelle")
        self.SubeListesi = QtWidgets.QAction(Anaekran)
        self.SubeListesi.setObjectName("SubeListesi")
        self.SinavyeriGuncelle = QtWidgets.QAction(Anaekran)
        self.SinavyeriGuncelle.setObjectName("SinavyeriGuncelle")
        self.KapasiteGuncelle = QtWidgets.QAction(Anaekran)
        self.KapasiteGuncelle.setObjectName("KapasiteGuncelle")
        self.actionDa_t_m_Yap = QtWidgets.QAction(Anaekran)
        self.actionDa_t_m_Yap.setObjectName("actionDa_t_m_Yap")
        self.cikis = QtWidgets.QAction(Anaekran)
        self.cikis.setObjectName("cikis")
        self.menusubeislemleri.addAction(self.SubeisimleriGuncelle)
        self.menusubeislemleri.addAction(self.SubeListesi)
        self.menusfizikiislemler.addAction(self.SinavyeriGuncelle)
        self.menusfizikiislemler.addAction(self.KapasiteGuncelle)
        self.menuBilgiler.addAction(self.OkulBilgileriGuncelle)
        self.menuBilgiler.addAction(self.menusubeislemleri.menuAction())
        self.menuBilgiler.addAction(self.menusfizikiislemler.menuAction())
        self.menuBilgiler.addAction(self.cikis)
        self.menudagitim.addAction(self.YeniDagitim.menuAction())
        self.menudagitim.addAction(self.EskiDagitimlar)
        self.menubar.addAction(self.menuBilgiler.menuAction())
        self.menubar.addAction(self.menudagitim.menuAction())

        self.retranslateUi(Anaekran)
        self.cikis.triggered.connect(Anaekran.close)
        QtCore.QMetaObject.connectSlotsByName(Anaekran)

    def retranslateUi(self, Anaekran):
        _translate = QtCore.QCoreApplication.translate
        Anaekran.setWindowTitle(_translate("Anaekran", "MainWindow"))
        self.label.setText(_translate("Anaekran", "<html><head/><body><p align=\"center\">Kelebek Sınav Dağıtım Programına Hoş Geldiniz <br/>Yapmak İstediğiniz İşlem İçin Menüleri Kullanınız</p></body></html>"))
        self.label_2.setText(_translate("Anaekran", "Okul A dı"))
        self.menuBilgiler.setTitle(_translate("Anaekran", "Bilgiler"))
        self.menusubeislemleri.setTitle(_translate("Anaekran", "Şube Bilgileri Giriş ve Güncelleme"))
        self.menusfizikiislemler.setTitle(_translate("Anaekran", "Fiziki Sınıf Giriş ve Güncelleme"))
        self.menudagitim.setTitle(_translate("Anaekran", "Dağıtım"))
        self.YeniDagitim.setTitle(_translate("Anaekran", "Yeni Dağıtım"))
        self.OkulBilgileriGuncelle.setText(_translate("Anaekran", "Okul Bilgilerini Güncelle"))
        self.EskiDagitimlar.setText(_translate("Anaekran", "Eski Dağıtımlar"))
        self.SubeisimleriGuncelle.setText(_translate("Anaekran", "Şube isimleri Güncelle"))
        self.SubeListesi.setText(_translate("Anaekran", "Şube Listelerini Güncelle"))
        self.SinavyeriGuncelle.setText(_translate("Anaekran", "Sınav Yeri Güncelle"))
        self.KapasiteGuncelle.setText(_translate("Anaekran", "Kapasiteleri Güncelle"))
        self.actionDa_t_m_Yap.setText(_translate("Anaekran", "Dağıtım Yap"))
        self.cikis.setText(_translate("Anaekran", "Çıkış"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Anaekran = QtWidgets.QMainWindow()
    ui = Ui_Anaekran()
    ui.setupUi(Anaekran)
    Anaekran.show()
    sys.exit(app.exec_())

