# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yenidagitim.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(803, 399)
        self.dagitim = QtWidgets.QPushButton(Form)
        self.dagitim.setGeometry(QtCore.QRect(720, 360, 75, 23))
        self.dagitim.setObjectName("dagitim")
        self.tab_bilgialanlari = QtWidgets.QTabWidget(Form)
        self.tab_bilgialanlari.setGeometry(QtCore.QRect(10, 10, 761, 351))
        self.tab_bilgialanlari.setObjectName("tab_bilgialanlari")
        self.bilgialanlari = QtWidgets.QWidget()
        self.bilgialanlari.setObjectName("bilgialanlari")
        self.label = QtWidgets.QLabel(self.bilgialanlari)
        self.label.setGeometry(QtCore.QRect(30, 20, 121, 16))
        self.label.setObjectName("label")
        self.sinav_adi = QtWidgets.QLineEdit(self.bilgialanlari)
        self.sinav_adi.setGeometry(QtCore.QRect(200, 20, 113, 20))
        self.sinav_adi.setObjectName("sinav_adi")
        self.label_2 = QtWidgets.QLabel(self.bilgialanlari)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 161, 16))
        self.label_2.setObjectName("label_2")
        self.sinav_tablosu_01 = QtWidgets.QTableWidget(self.bilgialanlari)
        self.sinav_tablosu_01.setGeometry(QtCore.QRect(350, 0, 401, 321))
        self.sinav_tablosu_01.setObjectName("sinav_tablosu_01")
        self.sinav_tablosu_01.setColumnCount(2)
        self.sinav_tablosu_01.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sinav_tablosu_01.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinav_tablosu_01.setHorizontalHeaderItem(1, item)
        self.sinav_tablosu_01.horizontalHeader().setDefaultSectionSize(200)
        self.label_5 = QtWidgets.QLabel(self.bilgialanlari)
        self.label_5.setGeometry(QtCore.QRect(40, 140, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{rgb(255, 0, 0)}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.sinav_sayisi = QtWidgets.QSpinBox(self.bilgialanlari)
        self.sinav_sayisi.setGeometry(QtCore.QRect(200, 70, 42, 22))
        self.sinav_sayisi.setMinimum(1)
        self.sinav_sayisi.setObjectName("sinav_sayisi")
        self.tab_bilgialanlari.addTab(self.bilgialanlari, "")
        self.sube_bilgileri = QtWidgets.QWidget()
        self.sube_bilgileri.setObjectName("sube_bilgileri")
        self.sinav_tablosu_02 = QtWidgets.QTableWidget(self.sube_bilgileri)
        self.sinav_tablosu_02.setGeometry(QtCore.QRect(450, 0, 271, 321))
        self.sinav_tablosu_02.setObjectName("sinav_tablosu_02")
        self.sinav_tablosu_02.setColumnCount(1)
        self.sinav_tablosu_02.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sinav_tablosu_02.setHorizontalHeaderItem(0, item)
        self.label_6 = QtWidgets.QLabel(self.sube_bilgileri)
        self.label_6.setGeometry(QtCore.QRect(60, 70, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{rgb(255, 0, 0)}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.sube_bilgileri)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{rgb(255, 0, 0)}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.tab_bilgialanlari.addTab(self.sube_bilgileri, "")
        self.sinav_yerleri = QtWidgets.QWidget()
        self.sinav_yerleri.setObjectName("sinav_yerleri")
        self.sinav_tablosu_03 = QtWidgets.QTableWidget(self.sinav_yerleri)
        self.sinav_tablosu_03.setGeometry(QtCore.QRect(340, 0, 331, 321))
        self.sinav_tablosu_03.setObjectName("sinav_tablosu_03")
        self.sinav_tablosu_03.setColumnCount(2)
        self.sinav_tablosu_03.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sinav_tablosu_03.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinav_tablosu_03.setHorizontalHeaderItem(1, item)
        self.label_3 = QtWidgets.QLabel(self.sinav_yerleri)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 171, 16))
        self.label_3.setObjectName("label_3")
        self.tab_bilgialanlari.addTab(self.sinav_yerleri, "")

        self.retranslateUi(Form)
        self.tab_bilgialanlari.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Yeni Dağıtım"))
        self.dagitim.setText(_translate("Form", "Dağıtımı Yap"))
        self.label.setText(_translate("Form", "Sınav Adı Giriniz"))
        self.label_2.setText(_translate("Form", "Yapılacak Sınav Sayısını Giriniz"))
        item = self.sinav_tablosu_01.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Sınav Sayısı"))
        item = self.sinav_tablosu_01.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Sınav Adı * Mutlaka Doldurun"))
        self.label_5.setText(_translate("Form", "Bilgileri Tam ve Eksiksiz Giriniz"))
        self.tab_bilgialanlari.setTabText(self.tab_bilgialanlari.indexOf(self.bilgialanlari), _translate("Form", "Bilgi Alanlari"))
        item = self.sinav_tablosu_02.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Şube Adı"))
        self.label_6.setText(_translate("Form", "Şubeler İçin Sınavları Tercih Ediniz"))
        self.label_7.setText(_translate("Form", "Sınav Seçilmeyen Sınıflar Dağıtılmayacaktır !!!"))
        self.tab_bilgialanlari.setTabText(self.tab_bilgialanlari.indexOf(self.sube_bilgileri), _translate("Form", "Şube Bilgileri"))
        item = self.sinav_tablosu_03.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Salon Adı"))
        item = self.sinav_tablosu_03.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Salon Seçimi"))
        self.label_3.setText(_translate("Form", "Sınav Yapılacak Salonları Seçiniz"))
        self.tab_bilgialanlari.setTabText(self.tab_bilgialanlari.indexOf(self.sinav_yerleri), _translate("Form", "Sınav Yerleri"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

